bingo:
	gcc -Wall -g bingo.c -o /misc/bingo.out
run-bingo:
	./misc/bingo.out < misc/bingo_input.txt

biblioteca:
	gcc -Wall -g biblioteca.c -o ./misc/biblioteca.out

run-biblioteca:
	./misc/biblioteca.out < misc/biblioteca_input.txt
